#!/bin/sh

cd ~/os161/src || exit
./configure
# building the userland
# only builds the clibs and testbin/test
# everything else disabled
bmake includes
bmake depend -j33 #pretty fast on M* Macs
bmake -j33
bmake install

# building the kernel
cd kern/conf || exit
./config DUMBVM
cd ../compile/DUMBVM || exit
bmake depend -j33 #pretty fast on M* Macs
bmake -j33
bmake install